Fix docker/podman problems - part 4 - final

diff --git a/API/Dockerfile b/API/Dockerfile
--- a/API/Dockerfile
+++ b/API/Dockerfile
@@ -8,8 +8,11 @@ ARG BUILD_CONFIGURATION=Development
 WORKDIR /src
 ADD . ./API
 WORKDIR /src/API
+RUN exec bash # switch the shell to BASH
 RUN pwd
 RUN ls -la
+RUN chmod +x ./dotenv-check && ./dotenv-check
+RUN if [ "$?" -ne 0 ]; then exit 1; fi # Check exit code
 RUN rm -r ./obj ./bin
 RUN dotnet restore .
 RUN dotnet build . -c $BUILD_CONFIGURATION -o /app/build
